version: '3'
services:
  git-test:
    build:
      context: ..
      dockerfile: ./Dockerfile
    volumes:
      - ..:/workspace
      - ./.bashrc:/root/.bashrc
      - ./git/:/root/git
    command: /bin/sh -c "while sleep 1000; do :; done"
